language: php

php:
  - '5.6.28'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script:
  - travis_retry curl -s http://getcomposer.org/installer | php
  - travis_retry php composer.phar install

# Explicitly use the phpunit from composer, not any system-wide found
script: 
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml --testdox tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
