language: php

php:
  - '7.0.17'
  - '7.0'
  - '7.1.2'
# https://github.com/sebastianbergmann/phpunit/issues/2581
#  - hhvm
  - nightly

before_script:
  - travis_retry curl -s http://getcomposer.org/installer | php
  - travis_retry php composer.phar install -n

# Explicitly use the phpunit from composer, not any system-wide found
script: 
#  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml --testdox tests
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml tests

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Not working with PHP :-(
# https://github.com/ottlinger/hornherzogen/issues/12
#addons:
#  srcclr: true

addons:
  apt:
    packages:
    - sendmail 
